services:
  product_db:
    image: postgres:16-alpine
    container_name: product_db
    environment:
      - 'POSTGRES_DB=product_db'
      - 'POSTGRES_USER=${DATABASE_USERNAME}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
    ports:
      - '5432:5432'
